model = "gpt-5.2-codex"

approval = "prompt"
sandbox = "local"
allowed_paths = []
network_access = true

telemetry = false
model_reasoning_effort = "medium"

[projects."/Users/pgollucci/.p6/p6m7g8-dotfiles/*"]
trust_level = "trusted"

[projects."/Users/pgollucci/.p6/p6m7g8-actions"]
trust_level = "trusted"

[projects."/Users/pgollucci/.p6/p6m7g8"]
trust_level = "trusted"

[projects."/Users/pgollucci/.p6/pgollucci"]
trust_level = "trusted"

[projects."/Users/pgollucci/src/github.com/work/arkestro"]
trust_level = "trusted"

[projects."/Users/pgollucci/.p6"]
trust_level = "trusted"

[projects."/Users/pgollucci/.p6/p6m7g8-dotfiles/p6common"]
trust_level = "trusted"

[notice]
hide_full_access_warning = true
